spring.application.name=PasteApp
#spring.data.mongodb.host=localhost
#spring.data.mongodb.port=27017
spring.data.mongodb.uri=mongodb+srv://pasteapprohit:rohitpasteapp@cluster0.p3z2e.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
spring.data.mongodb.database=pastes
logging.level.org.springframework.security=DEBUG